# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='author_img',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
