# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
                ('cc_myself', models.BooleanField()),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
