# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170617_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category'),
        ),
    ]
