# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170620_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
