# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_delete_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
