# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170617_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
