# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20170622_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
