# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=36),
        ),
    ]
