# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, default='这人很帅,什么都没说', max_length=128)),
                ('avatar', models.FileField(blank=True, default='/media/user/default.jpg', upload_to='media/user/img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
