# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, default='/media/user/default.jpg', upload_to='user/img'),
        ),
    ]
