# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170622_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, default='这人很帅,什么都没说', max_length=128),
        ),
    ]
